version: "3.9"
services:
  api-database:
    image: mongo:5.0
    container_name: "dichlowan-db"
    ports:
      - "27017:27017"
    volumes: 
      - ./data:/data/db
    # networks: 
    #   - mongo-compose-network
  # mongo-express:
  #   image: mongo-express
  #   container_name: "dichlowan-db-ui"
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: dichlowan-db
  #   depends_on:
  #     - api-database
  #   networks: 
  #     - mongo-compose-network 
  smpt-mail-server:
    # https://github.com/maildev/maildev
    image: maildev/maildev
    container_name: "dichlowan-mail-serv"
    command: bin/maildev --web 80 --smtp 25 --incoming-user dichlowan --incoming-pass dichlowan
    ports:
      - "1080:80"
      - "1025:25"

# networks:
#   mongo-compose-network:
#     driver: bridge
